version: '3.0'

services:
  api:
    build: backend
    command: ["flask", "run", "--host=0.0.0.0", "--debug"]
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    build: frontend
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - ./frontend:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '5173:5173'
    depends_on:
      - api

volumes:
  node-modules: